version: "3.9"

services:
  api-gateway:
    build:
      context: ./microservices/api-gateway
      dockerfile: Dockerfile
    container_name: uchat-api-gateway
    ports:
      - "5000:5000"
    environment:
      USER_SERVICE: http://user-service:5001
      CHAT_SERVICE: http://chat-service:5002
      EMAIL_SERVICE: http://email-service:5003

  user-service:
    build:
      context: ./microservices/user-service
      dockerfile: Dockerfile
    container_name: uchat-user-service
    ports:
      - "5001:5001"
    environment:
      CHAT_SERVICE: http://chat-service:5002
      EMAIL_SERVICE: http://email-service:5003

  chat-service:
    build:
      context: ./microservices/chat-service
      dockerfile: Dockerfile
    container_name: uchat-chat-service
    ports:
      - "5002:5002"
    environment:
      USER_SERVICE: http://user-service:5001
      EMAIL_SERVICE: http://email-service:5003

  email-service:
    build:
      context: ./microservices/email-service
      dockerfile: Dockerfile
    container_name: uchat-email-service
    ports:
      - "5003:5003"
    environment:
      USER_SERVICE: http://user-service:5001
      CHAT_SERVICE: http://chat-service:5002
