version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: uchat-api-gateway
    ports:
      - "5000:5000"
    env_file:
      - ./api-gateway/.env.local
    depends_on:
      - auth-service
      - chat-service
    volumes:
      - ./api-gateway:/app

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: uchat-auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env.local
    depends_on:
      - email-service
    volumes:
      - ./auth-service:/app

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: uchat-chat-service
    ports:
      - "5002:5002"
    env_file:
      - ./chat-service/.env.local
    volumes:
      - ./chat-service:/app

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    container_name: uchat-email-service
    ports:
      - "5003:5003"
    env_file:
      - ./email-service/.env.local
    volumes:
      - ./email-service:/app
